server:
  port: 9000

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost